brew "fish"
brew "starship"
brew "git"
brew "tmux"
brew "rsync"
brew "fzf"
brew "bat"
brew "prettyping"
brew "tldr"
brew "ripgrep"
brew "exa"
brew "httpie"
brew "fnm"
brew "mistertea/et/et"
brew "neovim", args: ["--HEAD"]
brew "universal-ctags/universal-ctags/universal-ctags", args: ["--HEAD"]
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "alacritty"
cask "karabiner-elements"
cask "alfred"
cask "hammerspoon"
cask "google-backup-and-sync"
cask "notion"
