#!/usr/bin/env bash

echo "Executing the OSX specific setup..."

ask_password_for() {
  local message=$1
  local pass_key=$2
  if [[ "$(security find-generic-password -a $USER -s $pass_key -w 2> /dev/null)" ]]; then
    echo "Password for '$message' and key '$pass_key' already defined."
    return
  fi
  echo -n "$message: "
  read -s password
  echo
  security add-generic-password -a $USER -s $pass_key -w $password
}

command_exists() {
  hash $1 2> /dev/null
}

if ! command_exists brew; then
  echo "Installing brew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "brew update... (can take a while)"
brew update
brew install macvim --with-lua --with-override-system-vim
brew install git bash-completion tmux mosh bash-git-prompt rsync

# install homebrew-cask
brew tap caskroom/cask
# so we can install the fira-code code
brew tap caskroom/fonts

# essential
brew cask install \
  atom \
  caffeine \
  imagealpha \
  imageoptim \
  iterm2 \
  spectacle \
  font-fira-code

# Based on https://github.com/mathiasbynens/dotfiles/blob/master/.osx
# Decreases the delay repetition on keyboard
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=' '

# Menu bar: show remaining battery time (on pre-10.8); hide percentage
defaults write com.apple.menuextra.battery ShowPercent -string "NO"
defaults write com.apple.menuextra.battery ShowTime -string "YES"

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: allow text selection in Quick Look
defaults write com.apple.finder QLEnableTextSelection -bool true

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true

# Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0
# Open and save files as UTF-8 in TextEdit
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

# Prevent Time Machine from prompting to use new hard drives as backup volume
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# setup passwords
ask_password_for "Personal email" personal_email
ask_password_for "SparkPost email API key" sparkpost_email_api_key
ask_password_for "Router's MAC address 2.4ghz" mac_address_24ghz
ask_password_for "Router's MAC address 5.0ghz" mac_address_50ghz

# setup timemachine backup
